import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base = process.env.BASE_URL || 'http://127.0.0.1:4175';
const browser = await chromium.launch({channel:'chromium',args:['--use-angle=metal']});
const results = [];
try {
  const page = await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  await page.goto(base); await page.waitForFunction(()=>window.cellAtlas?.ready);
  assert.equal(await page.locator('#clipping').isVisible(),true,'section slider is available without obstructing the model');
  assert.equal(await page.locator('#clipping').evaluate(el=>!!el.closest('dialog')),false);
  const box = await page.locator('#clipping').boundingBox();
  assert.ok(box.height>=44,'slider has a touch-sized hit area');
  const cdp=await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+14,y:box.y+box.height/2,id:1}]});
  for(let i=1;i<=8;i++) await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+14+(box.width-28)*.65*i/8,y:box.y+box.height/2,id:1}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const value = Number(await page.locator('#clipping').inputValue());
  assert.ok(value>45&&value<85,`CDP touch drag changes native slider: ${value}`);
  assert.equal(await page.locator('#clipping-value').textContent(),`${value}%`);
  await page.locator('[data-depth="0"]').click();
  assert.equal(await page.evaluate(()=>window.cellAtlas.diagnostics().clipping),0);
  results.push({test:'inline section control and real CDP touch drag',value,status:'passed'});
  const diagnostics=()=>page.evaluate(()=>window.cellAtlas.diagnostics());
  await page.locator('#clipping').fill('100');
  await page.locator('#structures-open').click();
  await page.locator('[data-structure="mitochondria"]').click();
  let d=await diagnostics();
  assert.equal(d.clipping,0,'list selection reveals clipped structures');
  assert.ok(d.target.every((n,i)=>Math.abs(n-d.focusPoint[i])<1e-8),'list selection frames the new structure');
  await page.locator('#isolate-button').click();
  await page.locator('#clipping').fill('100');
  const previous=d.target;
  await page.getByRole('button',{name:'Next structure',exact:true}).click();
  d=await diagnostics();
  assert.equal(d.isolated,true,'isolation follows the new selection');
  assert.equal(d.clipping,0);
  assert.notDeepEqual(d.target,previous,'camera no longer targets the old organelle');
  assert.ok(d.target.every((n,i)=>Math.abs(n-d.focusPoint[i])<1e-8));
  assert.ok(d.visibleIds.includes(d.selected));
  await page.locator('#settings-open').click(); await page.locator('#membrane-toggle').uncheck();
  await page.getByRole('button',{name:'Close view settings'}).click();
  await page.locator('#structures-open').click(); await page.locator('[data-structure="membrane"]').click();
  d=await diagnostics(); assert.equal(d.membrane,true,'selected membrane is revealed');
  assert.ok(d.visibleIds.includes('membrane'));
  await page.getByRole('button',{name:'Next structure',exact:true}).click();
  assert.equal((await diagnostics()).selected,'nucleus','next wraps last to first');
  await page.getByRole('button',{name:'Previous structure',exact:true}).click();
  assert.equal((await diagnostics()).selected,'membrane','previous wraps first to last');
  await page.locator('#clipping').fill('100'); await page.locator('#focus-button').click();
  assert.equal((await diagnostics()).clipping,0,'focus reveals a clipped selection');
  await page.getByRole('button',{name:'Whole cell — reset view',exact:true}).click();
  d=await diagnostics();
  assert.equal(d.isolated,false); assert.equal(d.clipping,0); assert.equal(d.clippingConstant,9);
  assert.deepEqual(d.target,[0,0,0]); assert.equal(d.visibleIds.length,12);
  assert.equal(d.rotating,false,'reduced motion never implicitly starts rotation');
  results.push({test:'list/next/previous reveal, follow isolation, focus and wrap; whole-cell reset',status:'passed'});
  assert.equal(await page.getByRole('button',{name:'Whole cell — reset view',exact:true}).count(),1,'visible Whole cell label is also the accessible name');
  await page.close();
  for (const [width,height] of [[320,568],[390,844],[568,320],[844,390]]) {
    const p=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
    await p.goto(base); await p.waitForFunction(()=>window.cellAtlas?.ready);
    assert.equal(await p.evaluate(()=>document.getElementById('app').offsetHeight<=innerHeight),true,`${width}x${height}: app fits`);
    const canvas=await p.locator('canvas').boundingBox();
    assert.ok(canvas.height>=180,`${width}x${height}: model remains usable (${canvas.height}px)`);
    for(let i=0;i<12;i++) {
      const obstructed=await p.locator('button:visible,#clipping').evaluateAll(elements=>elements.filter(el=>{
        const r=el.getBoundingClientRect(), hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);
        return r.width<44||r.height<44||r.top<0||r.bottom>innerHeight||r.left<0||r.right>innerWidth||!el.contains(hit);
      }).map(el=>el.id||el.textContent.trim()));
      assert.deepEqual(obstructed,[],`${width}x${height}: all structures have reachable 44px controls`);
      await p.locator('#next-structure').click();
    }
    const range=await p.locator('#clipping').boundingBox();
    const touch=await p.context().newCDPSession(p);
    const beforeDrag=await p.evaluate(()=>window.cellAtlas.diagnostics().camera);
    await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:range.x+14,y:range.y+22,id:1}]});
    for(let step=1;step<=6;step++) await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:range.x+14+(range.width-28)*.7*step/6,y:range.y+22,id:1}]});
    await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    const depth=Number(await p.locator('#clipping').inputValue());
    assert.ok(depth>=60&&depth<=80,`${width}x${height}: real touch slider works (${depth}%)`);
    const afterDrag=await p.evaluate(()=>window.cellAtlas.diagnostics().camera);
    assert.ok(afterDrag.every((n,i)=>Math.abs(n-beforeDrag[i])<1e-8),'dragging section depth does not orbit the model');
    await p.locator('#clipping').focus(); await p.keyboard.press('Home');
    assert.equal(await p.evaluate(()=>window.cellAtlas.diagnostics().clippingConstant),9,'keyboard zero matches whole-cell reset');
    await p.locator('#reset-button').click();
    await p.screenshot({path:`evidence/usability-${width}x${height}.png`});
    results.push({test:`${width}x${height} all twelve selections, touch slider and target reachability`,touchDepth:depth,canvasHeight:canvas.height,status:'passed'});
    await p.close();
  }
  const fallback=await browser.newPage({viewport:{width:320,height:568},reducedMotion:'reduce'});
  await fallback.goto(base+'/?webgl=off'); await fallback.waitForFunction(()=>window.cellAtlas?.ready);
  assert.equal(await fallback.locator('#section-control').isVisible(),false,'unavailable 3D control is not offered');
  assert.equal(await fallback.locator('.viewport-tools').isVisible(),false,'disabled toolbar does not obscure fallback reading');
  await fallback.locator('#next-structure').click();
  assert.equal(await fallback.locator('#selected-name').textContent(),'Nucleolus');
  await fallback.locator('#details-open').click();
  assert.ok(await fallback.locator('#detail-sources a').count()>0);
  await fallback.keyboard.press('Escape');
  await fallback.screenshot({path:'evidence/usability-fallback.png'});
  results.push({test:'WebGL fallback supports next/previous and sourced field notes',status:'passed'});
  await fallback.close();
  const animated=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'no-preference'});
  await animated.goto(base); await animated.waitForFunction(()=>window.cellAtlas?.ready);
  await animated.locator('#next-structure').click(); await animated.locator('#next-structure').click();
  await animated.waitForFunction(()=>!window.cellAtlas.diagnostics().transitioning);
  const final=await animated.evaluate(()=>window.cellAtlas.diagnostics());
  assert.equal(final.selected,'rough-er');
  assert.ok(final.target.every((n,i)=>Math.abs(n-final.focusPoint[i])<1e-8),'rapid navigation ends at last requested part');
  results.push({test:'animated rapid navigation ends at the newest selection',status:'passed'});
  await animated.close();
  console.log(JSON.stringify(results,null,2));
} finally { await fs.writeFile('evidence/usability-results.json',JSON.stringify(results,null,2)); await browser.close(); }
